#!/usr/bin/env bash
#This script displays FizzBuzz when the number is a multiple of 3 and 5, Fizz when the number is multiple of 3, Buzz when the number is a multiple of 5. Otherwise, displays the number in a list format
for i in {1..100} ; do
	if ! ((i % 15 )) ; then
		echo "FizzBuzz"
elif ! ((i % 3)); then
echo "Fizz"
elif ! ((i % 5)); then
echo "Buzz"
else
echo "$i"
fi
done
