#!/usr/bin/env bash
#This script creates the file /var/run/myscript.pid containing its PID, displays "To infinity and beyond" indefinitely, "I hate the kill command" when receiving a SIGTERM signal, "Y U no love me?!" when receiving a SIGINT signal and deletes the file "/var/run/myscript.pid" and terminates itself when receiving a SIGQUIT or SIGTERM signal
clean_up='rm /var/run/myscript.pid; exit $?'

echo $$ > "/var/run/myscript.pid"
trap 'echo "I hate the kill command"; '"$clean_up" SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap ''"$clean_up" SIGQUIT

while true; do
	echo "To infinity and beyond"
done
