#!/usr/bin/env bash
# This script Creates the file /var/run/myscript.pid containing its PID Displays To infinity and beyond indefinitely Displays I hate the kill command when receiving a SIGTERM signal Displays Y U no love me?! when receiving a SIGINT signal Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
while [[ 1 -eq 1 ]]; do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done
